const getDefaultDate = () => new Date().toISOString().split("T")[0];

export const initialDeviceStates = {
  laptop: {
    nr_seryjny: "",
    model: "",
    podzial_uprawnien: 0,
    system_operacyjny: "",
    rodzaj_dysku: "",
    data_wymiany_dysku: "",
    ram: 0,
    karta_graficzna: 0,
    plyta_glowna: "",
    zasilacz: "",
    program_zdalny: "",
    id_programu: "",
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  alarm: {
    model: "",
    ilosc_czujek: 0,
    podzial_uprawnien: 0,
    ilosc_klawiatur: 0,
    ilosc_modulow: 0,
    system_rozproszony: 0,
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  pc: {
    nr_seryjny: "",
    podzial_uprawnien: 0,
    system_operacyjny: "",
    rodzaj_dysku: "",
    data_wymiany_dysku: "",
    ram: 0,
    karta_graficzna: 0,
    plyta_glowna: "",
    zasilacz: "",
    program_zdalny: "",
    id_programu: "",
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  anteny: {
    czasza: 0,
    antena_dvbt: 0,
    antena_radiowa: 0,
    zwrotnica: 0,
    ilosc_rozgaleznikow: 0,
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
};
