const getDefaultDate = () => new Date().toISOString().split("T")[0];

export const initialDeviceStates = {
  laptop: {
    nr_seryjny: "",
    model: "",
    podzial_uprawnien: 0,
    system_operacyjny: "",
    rodzaj_dysku: "",
    data_wymiany_dysku: "",
    ram: 0,
    karta_graficzna: 0,
    plyta_glowna: "",
    zasilacz: "",
    program_zdalny: "",
    id_programu: "",
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  alarm: {
    model: "",
    ilosc_czujek: 0,
    podzial_uprawnien: 0,
    ilosc_klawiatur: 0,
    ilosc_modulow: 0,
    system_rozproszony: 0,
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  pc: {
    nr_seryjny: "",
    podzial_uprawnien: 0,
    system_operacyjny: "",
    rodzaj_dysku: "",
    data_wymiany_dysku: "",
    ram: 0,
    karta_graficzna: 0,
    plyta_glowna: "",
    zasilacz: "",
    program_zdalny: "",
    id_programu: "",
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  anteny: {
    czasza: 0,
    antena_dvbt: 0,
    antena_radiowa: 0,
    zwrotnica: 0,
    ilosc_rozgaleznikow: 0,
    uwagi: "",
    notatki: "",
    dataOD: getDefaultDate(),
    dataDO: null,
  },
  kamery: {
    nr_seryjny: "",
    mac: "",
    model: "",
    podzial_uprawnien: 0,
    portHTTP: "",
    portDANE: "",
    ipWewnetrzne: "",
    uwagi: "",
    notatki: "",
    dataOD: new Date().toISOString().split("T")[0],
    dataDO: null,
  },
  nvr: {
    nr_seryjny: "",
    model: "",
    mac: "",
    podzial_uprawnien: 0,
    model_dysku: "",
    wielkoscDysku: 0,
    dataWymianyDysku: "",
    portHTTP: 0,
    portDANE: 0,
    iloscKamer: 0,
    ipWewnetrzne: "",
    ipZewnetrzne: "",
    p2p: 0,
    uwagi: "",
    notatki: "",
    dataOD: new Date().toISOString().split("T")[0],
    dataDO: null,
  },
  pozostale: {
    nazwa: "",
    opis: "",
    zasadaDzialania: "",
    uwagi: "",
    notatki: "",
    dataOD: new Date().toISOString().split("T")[0],
    dataDO: null,
  },
  routers: {
    nr_seryjny: "",
    model: "",
    macWAN: "",
    ipwew: "",
    ipzew: "",
    podzial_uprawnien: 0,
    portHTTP: 0,
    portDANE: 0,
    VPNklien: 0,
    VPNzazadzanie: 0,
    uwagi: "",
    notatki: "",
    dataOD: new Date().toISOString().split("T")[0],
    dataDO: null,
  },
  oprogramowania: {
    nazwa: "",
    opis: "",
    klucz: "",
    administrator: 0,
    przypisany_do: "",
    data_aktywacji: "",
    data_waznosci: "",
    uwagi: "",
    notatki: "",
    dataOD: new Date().toISOString().split("T")[0],
    dataDO: null,
  },
};

export const initialRaportStates = {
  raport: {
    id_klienta: null,
    status: 1,
    tytul: "",
    priorytet: 1,
    data: new Date().toISOString().split("T")[0],
    godzina: new Date().toTimeString().split(" ")[0],
    tresc: "",
  },

  ticket: {
    // id: null,
    id_klienta: null,
    status: 0,
    tytul: "",
    priorytet: 0,
    data: "",
    godzina: "",
  },

  message: {
    // id: null,
    id_ticket: null,
    id_klienta: null,
    data: "",
    godzina: "",
    tresc: "",
  },
};
